// This file is auto-generated by the CMS
// Add new event filenames here when creating events through the admin panel
export const eventFiles = [
  'campus-tour.md',
  'diwali-mela.md',
  // Add more event files as they are created
];

export const boardFiles = [
  // Add board member files as they are created
];

export const resourceFiles = [
  // Add resource files as they are created
];
